openapi: "3.0.0"
info:
  version: 1.0.0
  title: Thank You For Using SwaggerBake
  license:
    name: YOUR-LICENSE-HERE
servers:
  - url: YOUR-SERVER-HERE
paths:

definitions:

components:
  schemas:
    Exception:
      type: object
      properties:
        code:
          type: integer
          example: 500
        url:
          type: string
          example: /url/path
        message:
          type: string
          example: Internal Error
