# SwaggerBake Vendor Extensions
x-swagger-bake:
  components:
    parameters:
      paginatorPage:
        name: page
        in: query
        required: false
        schema:
          type: integer
      paginatorLimit:
        name: limit
        in: query
        required: false
        schema:
          type: integer
      paginatorSort:
        name: direction
        in: query
        required: false
        schema:
          type: string
      paginatorDirection:
        name: direction
        in: query
        required: false
        schema:
          type: string
          enum:
            - asc
            - desc
    schemas:
      HalJson-Item:
        type: object
        properties:
          links:
            type: object
            properties:
              self:
                type: object
                properties:
                  href:
                    type: string
                    format: url
                    example: /entity/:id
      HalJson-Collection:
        type: object
        properties:
          links:
            type: object
            properties:
              self:
                type: object
                properties:
                  href:
                    type: string
                    format: url
                    example: /collection
              next:
                type: object
                properties:
                  href:
                    type: string
                    format: url
                    example: /collection?page=:id
              prev:
                type: object
                properties:
                  href:
                    type: string
                    format: url
                    example: /collection?page=:id
              first:
                type: object
                properties:
                  href:
                    type: string
                    format: url
                    example: /collection?page=:id
              properties:
                href:
                  type: string
                  format: url
                  example: /collection?page=:id
            last:
              type: object
              properties:
                href:
                  type: string
                  format: url
                  example: /collection?page=:id